config/routes.rb
Rails.application.routes.draw do

  # get 'orders/index'
  # get 'orders/show'

  resources :orders

root to: 'pages#home'

resources :line_items

  get '/basket' => 'baskets#user_basket'
  post '/basket/add_item' => 'baskets#add_item'
  get '/basket/check_out' => 'baskets#check_out'
  get '/basket/edit' => 'baskets#user_basket_edit'

resources :baskets

  get '/users/edit' => 'users#edit'
resources :users

resources :products

#login/logout routes
get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

get '/payment' => 'payment#pay'
post '/payment' => 'payment#process_payment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :line_items, ->{order(:created_at)}
  belongs_to :user, optional:true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :basket
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :basket

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :fetch_user



  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by id:session[:user_id]
    end

    session[:user_id] = nil unless @current_user.present?
  end


  def check_if_logged_in
    #if the current request is coming from an user that is not logged in, redirect them to the log in page. Any controller actions that should be available only to logged in users can then run this method before they do their work, ie. we can lock down those routes
    unless @current_user.present?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end #check if check_if_logged_in

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  before_action :check_if_logged_in

  def user_basket
  end

  def add_item
    item = @current_user.basket.line_items.find_by product_id: params[:product_id]
    if item.present?
      #if there is a line_item already we will amend the quantity
      item.update quantity: (item.quantity + params[:quantity].to_i)

    else
      LineItem.create(
      product_id: params[:product_id],
      quantity: params[:quantity],
      basket_id: @current_user.basket.id

      )
    end #end of the else, ie:create line_item
    redirect_to basket_path
  end

  def index
    @baskets = Basket.all
  end

  def show
    @basket = Basket.find params[:id]
  end

  def check_out
    @total = 0
    @current_user.basket.line_items.each do |item|
      @total += item.product.price*item.quantity

    end


  end

  def edit

  end

  def user_basket_edit

  end

  def update
  end

  def destroy
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    item = @current_user.basket.line_items.find_by product_id: params[:line_item][:product_id]
    item.update quantity: params[:line_item][:quantity]

    redirect_to basket_path
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :check_if_logged_in
  def index
    @orders = Order.where user_id:@current_user.id
  end

  def show

    @order = params[:id]
    @order_items = OrderItem.where order_id:params[:id]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  before_action :check_if_logged_in

  def pay
    @token = client_token

    @total = 0
    @current_user.basket.line_items.each do |item|
      @total += item.product.price*item.quantity
    end
  end

  def braintreegateway
    gateway = Braintree::Gateway.new(
      :environment => :sandbox,
      :merchant_id => "q9w7d2k22r3492x3",
      :public_key => "gqx279w8nh7qvvrf",
      :private_key => "2b5033f5fd7a53fce390745ad308e719",
    )
  end

  def client_token
    # pass client_token to your front-end
    gateway = braintreegateway

    client_token = gateway.client_token.generate


  end

  def process_payment
    gateway = braintreegateway
    total = 0
    @current_user.basket.line_items.each do |item|
      total += item.product.price*item.quantity
    end
    result = gateway.transaction.sale(
      :amount => total,
      :payment_method_nonce => params[:nonce],
      :options => {
        :submit_for_settlement => true
      }
    )
    redirect_to products_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

#create
  def new
    @product = Product.new
  end

  def create
    product = Product.new product_params


    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      p response
      product.image=response["public_id"]
      product.save
    end

    redirect_to products_path

  end


  def index
    @products = Product.all

  end

  def show
    @product = Product.find params[:id]

  end


  def edit
    @product = Product.find params[:id]

  end

  def update
    product = Product.find params[:id]

    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      p response
      product.image=response["public_id"]
      product.save
    end

    product.update product_params
    redirect_to product_path(product.id)
  end


  def destroy
    Product.destroy params[:id]
    redirect_to products_path
  end

private

  def product_params
    params.require(:product).permit(:title, :price, :brand, :department, :description, :image )

  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email:params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email, username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil #this logs out out the user
    redirect_to login_path #go back to the login page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      @basket = Basket.create user_id:@user.id
      redirect_to root_path
    else
      render :new
    end


  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    user = User.find params[:id]

    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      p response
      user.image=response["public_id"]
      user.save
    end

    user.update user_params
    redirect_to root_path
  end


  def destroy
  end
end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/check_out.html.erb
<h1>Your basket is ready to go!</h1>

<h6>Please review order and enter payment details below</h6>
<br>

<div class="btn grey darken-4">
  <%= link_to "Edit Basket", basket_path %>

</div>

<div class="">

  <% @current_user.basket.line_items.each do |item| %>
      <p>
        Product: <%= item.product.title %>
      </p>
      <p>
        Quantity: <%= item.quantity %>
      </p>
      <p>
        <%= cl_image_tag item.product.image %>

      </p>

      Subtotal: AUD <%= item.product.price*item.quantity %>

  <% end %>
      <p>
        Total : <%= @total %>

      </p>

      <br>
  
  <a href='/payment' class="waves-effect waves-light btn-large">Pay</a>

</div>

app/views/baskets/destroy.html.erb
<h1>Baskets#destroy</h1>
<p>Find me in app/views/baskets/destroy.html.erb</p>

app/views/baskets/index.html.erb
<h1>Baskets#index</h1>
<p>Find me in app/views/baskets/index.html.erb</p>

<ul>

  <% @baskets.each do |basket| %>
  <li>
    <%= link_to basket.user_id, basket_path(basket.id) %>
  </li>
  <% end %>
</ul>

app/views/baskets/show.html.erb
<% if @basket.user_id == @current_user.id %>
<%= link_to 'Edit Basket', edit_basket_path(@basket.id) %>
<% end %>

<h1>Basket created by <%= @basket.user.username %> </h1>

app/views/baskets/user_basket.html.erb
<h1>Your basket!</h1>
<h6>Please review and update the quantity before checking out</h6>
<br>
<div class="btn grey darken-4">
<%= link_to "Check out", basket_check_out_path %>
</div>

<br>

<div class="">

  <% @current_user.basket.line_items.each do |item| %>
      Product: <%= item.product.title %>
      <br>
      <%= cl_image_tag item.product.image %>
      <p>
        Subtotal: AUD <%= item.product.price*item.quantity %>

      </p>
      <br>

        <div class="form">
        <%= form_for item do |f| %>

          <%= f.hidden_field :product_id, :value => item.product.id %>
          Qty<%= f.number_field :quantity, :value => item.quantity, :min =>1%>
          <div class="waves-effect waves-light btn">
            <%= f.submit "update quantity" %>
          </div>
          <br>
          <br>

        <% end  %>

      </div>

  <% end %>


</div>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/orders/index.html.erb
<h1>Your orders</h1>
<p>Please see below your order numbers</p>


<ul>

  <% @orders.each do |order| %>
  <li>
    <%= link_to order.id, order_path(order.id) %>
  </li>
  <% end %>
</ul>

app/views/orders/show.html.erb
<h1>Your Items Ordered</h1>

<p>Order #<%= @order %> </p>



<ul>

  <% @order_items.each do |order_item| %>
  <li>

    <%=  order_item.quantity %>
    x
    <%=  order_item.product.title %>
    <br>
    <%= cl_image_tag order_item.product.image %>

  </li>
  <% end %>
</ul>

app/views/products/_form.html.erb
<%= form_with model:@product, local:true, html: {multipart: true} do |f| %>

<%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
  <br>
  <%= f.label :department %>
  <%= f.text_field :department %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :image %>
  <%= f.cl_image_upload :image %>
  <br>

  <%= f.submit %>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h2>
  Edit Product: <%= @product.title %>
</h2>
  <% if @current_user.present? && @current_user.admin? %>
  <%= render partial: 'form' %>
  <% end %>

app/views/products/index.html.erb
<h1>GA Products</h1>


  <% if @current_user.present? && @current_user.admin? %>
    <%= link_to 'Add a New Product', new_product_path  %>
  <% end %>

  <ul>
    <% @products.each do |product| %>
    <li>
      <%= link_to product.title, product_path(product.id) %>
    </li>
    <% end %>
  </ul>

app/views/products/new.html.erb
<h2>
  New Product
</h2>

  <% if @current_user.present? && @current_user.admin? %>
  <%= render partial: 'form' %>
  
  <% end %>

app/views/products/show.html.erb
<h2>
<%= @product.title %>

</h2>

<div class="">

  <% if @current_user.present? && @current_user.admin? %>

  <%= link_to 'Edit Product', edit_product_path  %>

   <%= link_to 'Delete Product', product_path(@product.id), method:'delete' %>

   <% end %>

</div>



<div class="">

  <p>
    <strong>Price:</strong>
    AUD $ <%= @product.price %>
  </p>
  <p>
    <strong>Brand:</strong>
    <%= @product.brand %>
  </p>
  <p>
    <strong>Department:</strong>
    <%= @product.department %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <div class="form">


    <%= form_with url: basket_add_item_path, local:true do |f| %>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, :value =>1, :min =>1 %>
    <%= f.hidden_field :product_id, value: @product.id %>
    <div class="waves-effect waves-light btn">
      <%= f.submit 'Add'%>      
    </div>
    <%end %>

    </div>

  </p>


  <p>

    <%= cl_image_tag @product.image %>
  </p>




</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/edit.html.erb
<h2>
  Edit Profile: <%= @current_user.username %>
</h2>
  <% if @current_user.present? %>

  <%= form_with model:@current_user, local:true, html: {multipart: true} do |f| %>

  <%= f.label :username %>
    <%= f.text_field :username, value: @current_user.username %>
    <br>
    <%= f.label :image %>
    <%= f.cl_image_upload :image %>
    <br>

    <%= f.submit %>
  <% end %>






  <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2>Create an account</h2>

<% if @user.errors.full_messages.any? %>
Please correct the following errors
  <ul>
<% @user.errors.full_messages.each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  </ul>

<% end %>

<%= form_with model:@user, local:true do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>



  <%= f.submit 'Sign Up' %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>