config/routes.rb
Rails.application.routes.draw do

  # get 'orders/index'
  # get 'orders/show'

  resources :orders

root to: 'pages#home'

resources :line_items

  get '/basket' => 'baskets#user_basket'
  post '/basket/add_item' => 'baskets#add_item'
  get '/basket/check_out' => 'baskets#check_out'
  get '/basket/edit' => 'baskets#user_basket_edit'

resources :baskets

  get '/users/edit' => 'users#edit'
resources :users

resources :products

#login/logout routes
get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

get '/payment' => 'payment#pay'
post '/payment' => 'payment#process_payment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :line_items, ->{order(:created_at)}
  belongs_to :user, optional:true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :basket
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :basket

  has_secure_password
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  before_action :check_if_logged_in

  def user_basket
  end

  def add_item
    item = @current_user.basket.line_items.find_by product_id: params[:product_id]
    if item.present?
      #if there is a line_item already we will amend the quantity
      item.update quantity: (item.quantity + params[:quantity].to_i)

    else
      LineItem.create(
      product_id: params[:product_id],
      quantity: params[:quantity],
      basket_id: @current_user.basket.id

      )
    end #end of the else, ie:create line_item
    redirect_to basket_path
  end

  def index
    @baskets = Basket.all
  end

  def show
    @basket = Basket.find params[:id]
  end

  def check_out
    @total = 0
    @current_user.basket.line_items.each do |item|
      @total += item.product.price*item.quantity

    end


  end

  def edit

  end

  def user_basket_edit

  end

  def update
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :check_if_logged_in
  def index
    @orders = Order.where user_id:@current_user.id
  end

  def show

    @order = params[:id]
    @order_items = OrderItem.where order_id:params[:id]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  before_action :check_if_logged_in

  def pay
    @token = client_token

    @total = 0
    @current_user.basket.line_items.each do |item|
      @total += item.product.price*item.quantity
    end
  end

  def braintreegateway
    gateway = Braintree::Gateway.new(
      :environment => :sandbox,
      :merchant_id => "q9w7d2k22r3492x3",
      :public_key => "gqx279w8nh7qvvrf",
      :private_key => "2b5033f5fd7a53fce390745ad308e719",
    )
  end

  def client_token
    # pass client_token to your front-end
    gateway = braintreegateway

    client_token = gateway.client_token.generate


  end

  def process_payment
    gateway = braintreegateway
    total = 0
    @current_user.basket.line_items.each do |item|
      total += item.product.price*item.quantity
    end
    result = gateway.transaction.sale(
      :amount => total,
      :payment_method_nonce => params[:nonce],
      :options => {
        :submit_for_settlement => true
      }
    )
    redirect_to products_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email:params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email, username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil #this logs out out the user
    redirect_to login_path #go back to the login page
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      @basket = Basket.create user_id:@user.id
      redirect_to root_path
    else
      render :new
    end


  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    user = User.find params[:id]

    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      p response
      user.image=response["public_id"]
      user.save
    end

    user.update user_params
    redirect_to root_path
  end


  def destroy
  end
end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Amazing GA Shop</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>


  <body>
    <header>

<<<<<<< HEAD
      <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>

  

=======
>>>>>>> braintree
      <nav>
    <div class="nav-wrapper container">
      <ul>
        <li class="brand-logo"><%= link_to "The GA Shop" , root_path  %> </li>
      </ul>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Products", products_path %></li>
        <% if @current_user.present? %>
          <li><%= link_to "basket", basket_path %></li>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Edit profile", users_edit_path %></li>
          <li><%= link_to "Logout", login_path, method: 'delete'%></li>
        <% else %>
          <li><%= link_to "Login", login_path  %></li>
          <li><%= link_to "Sign Up", new_user_path  %></li>
        <% end %>

      </ul>
    </div>
  </nav>

   <ul class="sidenav" id="mobile-demo">
    <li><%= link_to "Products", products_path %></li>
    <% if @current_user.present? %>
      <li><%= link_to "basket", basket_path %></li>
      <li><%= link_to "Orders", orders_path %></li>
      <li><%= link_to "Edit profile", users_edit_path %></li>
      <li><%= link_to "Logout", login_path, method: 'delete'%></li>
    <% else %>
      <li><%= link_to "Login", login_path  %></li>
      <li><%= link_to "Sign Up", new_user_path  %></li>
    <% end %>

  </ul>



      <!-- <nav>
        <div class="nav-wrapper container" >
          <ul id="nav-mobile" class="left hide-on-med-and-down">

<<<<<<< HEAD
            <li> <%= link_to "The Amazing Shop", root_path %> </li>
=======
            <li> <%= link_to "The GA Shop", root_path %> </li>
>>>>>>> braintree
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <li><%= link_to "Products", products_path %></li>
            <% if @current_user.present? %>
              <li><%= link_to "basket", basket_path %></li>
              <li><%= link_to "Edit profile", users_edit_path %></li>
              <li><%= link_to "Logout", login_path, method: 'delete'%></li>
            <% else %>
              <li><%= link_to "Login", login_path  %></li>
              <li><%= link_to "Sign Up", new_user_path  %></li>
            <% end %>
          </ul>
        </div>
<<<<<<< HEAD
      </nav>

      <ul class="sidenav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
=======
      </nav> -->
>>>>>>> braintree

    </header>

    <main>


    <div class="container welcome">
        <% if @current_user.present? %>
        <%= "(Admin)" if @current_user.admin? %>  Welcome, <strong> <%= @current_user.username %> </strong>
        <p id="avatar"> <%= cl_image_tag @current_user.image %>
        <% else %> </p>
        <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <!-- </div>
    <div class="container">
      <footer>
        &copy Follow us on Facebook
      </footer>
    </div> -->

    <footer class="page-footer">

        <div class="footer-copyright">
          <div class="container">
          &copy 2020 General Assembly - Sydney
          <a class="grey-text text-lighten-4 right" href="#!">Follow us on Facebook</a>
          </div>
        </div>
      </footer>



  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user %>

<% else %>
<div class="jumbotron">
<h2>Welcome to the Amazing Shop!</h2>
<p class="lead">
  You will love Shopping with us! Log in or Sign up!
</p>
</div>
<% end %>

<div class="jumbotron">
<h3>
  Browse:
  <%= link_to "products", products_path %>
</h3>
</div>

<div id="logo">
  <img src="https://lh3.googleusercontent.com/pw/ACtC-3dLVXu8M6GERDpsdQxD0sB9PVFDHSS2l48fmDoPGy55RlKLt8hfDxyVH4gRxhUI--xSUi3fJQ38TzDFsLNJlGk2tvb9BJyQLlk6xN4_TUvTDBS45DITHS-P2x3t7ojJzZ2hZTsioTHfYcP1E543RLQvGA=s225-no?authuser=0')" alt="logo">
</div>